### ISSUE TITLE
YCM is not being compiled

### ISSUE THREAD

**Issue by pehowell** [pehowell/dotfiles#3]
```
ycm_core.[so|pyd|dll] not detected; you need to compile YCM before using it. Read the docs!
```

**Comment by pehowell** [comment]
Receiving error:

```
WARNING: this script is deprecated. Use the install.py script instead.
Please install CMake and retry.
Traceback (most recent call last):
  File "./install.py", line 32, in <module>
    Main()
  File "./install.py", line 21, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python2', '/home/pehowell/.yadr/vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '--clang-completer']' returned non-zero exit status 1
```
